### ISSUE TITLE
博主好

### ISSUE THREAD

**Issue by twsha** [LHY-huiyin/Semantic-Segmentation#1]
请问有没有写train_factseg的常规训练过程，原论文给出的分布式训练我无法跑通。

**Comment by LHY-huiyin** [comment]
> 
factseg?

**Comment by twsha** [comment]
你的lovada项目里的baseline有factseg这个模型，loveda和factseg两篇文章里都有junie wang这个作者。
factseg的源码有公开，里面的训练过程不是常规的，是通过apex分布式训练。

**Comment by LHY-huiyin** [comment]
> 你的lovada项目里的baseline有factseg这个模型，loveda和factseg两篇文章里都有junie wang这个作者。 factseg的源码有公开，里面的训练过程不是常规的，是通过apex分布式训练。

首先，你可以去找源代码看看，或许能跑通；其次，我通采用apex分布式训练是因为GPU存在不够用的情况，如果你的GPU允许，你可以不跑apex的程序。最后，用apex跑代码，容易报错。

**Comment by twsha** [comment]
> > 你的lovada项目里的baseline有factseg这个模型，loveda和factseg两篇文章里都有junie wang这个作者。 factseg的源码有公开，里面的训练过程不是常规的，是通过apex分布式训练。
> 
> 首先，你可以去找源代码看看，或许能跑通；其次，我通采用apex分布式训练是因为GPU存在不够用的情况，如果你的GPU允许，你可以不跑apex的程序。最后，用apex跑代码，容易报错。

谢谢，源码的评估过程已经跑通了，自己是单gpu，没能跑通他公布的apex训练源码。
